# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

def shared_pods
    pod 'Alamofire', '~> 4.7'
    pod 'RealmSwift'
    pod 'SwiftyJSON'
    pod 'Toast-Swift', '~> 3.0.1'
    pod 'PKHUD', '~> 5.0'
    pod 'SwiftLint'
end

target 'WeatherApp' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    # Pods for myTaxi
    shared_pods
end

target 'WeatherAppTests' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    # Pods for testing
    shared_pods
end
